from typing import Any, Optional, Tuple
from .versioning import VersionRange

class Artifact:
    artifact_id: str
    classifier: Optional[str]
    contents: Optional[Any]
    group_id: str
    type: str
    version: Optional[VersionRange]
    def __init__(self, coordinate: str) -> None: ...
    def __cmp__(self, other: Any) -> int: ...
    def __eq__(self, other: Any) -> bool: ...
    def __lt__(self, other: Any) -> bool: ...
    def __ne__(self, other: Any) -> bool: ...
    def __hash__(self) -> int: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def coordinate(self) -> str: ...
    def path(self) -> str: ...
