from typing import ClassVar, Union

class PymavenError(Exception):
    _template: ClassVar[Union[str, None]] = ...

class RepositoryError(PymavenError): ...
class MissingPathError(RepositoryError): ...
class ClientError(PymavenError): ...
class MissingArtifactError(PymavenError): ...
class ParseError(PymavenError): ...
class ArtifactParseError(ParseError): ...
class RestrictionParseError(ParseError): ...
class VersionRangeParseError(ParseError): ...
